#!/bin/sh

case "$1" in
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    service grafsy stop
    if [ "$1" = "purge" ] ; then
        userdel grafsy || true
    fi
  ;;
  *)
    echo "postrm called with unknown argument '$1'" 1>&2
    exit 1
  ;;
esac
