#!/bin/sh

# Abort if any command returns an error value
set -e

USER=grafsy
CONF=/etc/grafsy/grafsy.toml

# Following user part should be tested on both RPM and DEB systems
if ! getent group "${USER}" > /dev/null 2>&1 ; then
  groupadd --system "${USER}" --quiet
fi
GID=$(getent group "${USER}" | cut -d: -f 3)
if ! id "${USER}" > /dev/null 2>&1 ; then
  adduser --system --home /dev/null --no-create-home \
    --gid "${GID}" --shell /bin/false \
    "${USER}"
fi

if [ ! -e "${CONF}" ]; then
  echo "For use this software you have to create ${CONF} file. You could use /etc/grafsy/example/grafsy.toml as default"
else
  systemctl enable grafsy.service
  systemctl daemon-reload
  systemctl restart grafsy.service
fi
